require("thierschi.set")
require("thierschi.remap")
require("thierschi.theme")
require("thierschi.syntax")
require("thierschi.colourcolumn")
require("thierschi.whitespace")
require("thierschi.telescope")
